name: new_env
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.11.9
  - numpy=1.26.*
  - pandas=2.2.*
  - matplotlib=3.9.*
  - scikit-learn=1.5.*
  - scipy=1.14.*
  - pytorch=2.4.*
  - torchvision=0.19.*
  - nibabel=5.2.*
  - tqdm=4.66.*
  - plotly=5.23.*
  - statsmodels=0.14.*
  - seaborn=0.11.*
  - networkx=3.3.*
  - ipython=8.27.*
  - pip
  - pip:
    - monai==1.3.2
    - scikit-posthocs==0.9.0
    - wandb==0.17.5
    - einops==0.8.1
    - statannotations==0.7.0
    - shap==0.46
    - python-louvain==0.16
    - matplotlib-inline==0.1.7
    - pycomplexheatmap==1.7.7

  - torch
  - icecream